// Sample data matching the design canvas. Fictional people and companies.
// Replace per endpoint in lib/mail/api.ts as the Mail API ships.

import type {
  Campaign,
  CampaignDraft,
  Domain,
  Lead,
  LeadList,
  MailSettings,
  MailSummary,
  Mailbox,
  PreviewContact,
  Reply,
  SendCheck,
  VerificationSummary,
  Workspace,
} from "./types";

export const workspace: Workspace = {
  id: "ws_hubbly_internal",
  name: "Hubbly · Internal",
  subLabel: "Dogfood workspace",
  brand: "signal",
  mailEnabled: true,
  businessAddress: "2021 Guadalupe St, Austin, TX 78705",
  user: { name: "Vince R.", initials: "VR" },
};

export const summary: MailSummary = {
  sent30d: 14908,
  sentDeltaPct: 22,
  deliveredRate: 0.984,
  replyRate: 0.038,
  replies: 563,
  positiveReplies: 219,
  meetings: 41,
  meetingsThisWeek: 9,
  sendingToday: { used: 318, capacity: 360, capacityAfterWarmup: 480 },
  domains: 3,
  mailboxes: 12,
  mailboxesWarming: 4,
  repliesWaiting: 6,
  draftsWaiting: 1,
};

export const campaigns: Campaign[] = [
  {
    id: "cmp_pricing",
    name: "Pricing-page visitors — 48h follow-up",
    status: "running",
    audience: { source: "signal", label: "Identified visitors · /pricing 2+ visits", count: 1284, excluded: 212 },
    sent: 2140,
    total: 3000,
    replyRate: 0.068,
    positiveReplies: 58,
    meetings: 12,
    updatedAt: "2026-09-23",
  },
  {
    id: "cmp_agencies",
    name: "Agencies — partner program",
    status: "running",
    audience: { source: "csv", label: "4,812 contacts · marketing agencies, US", count: 4812, excluded: 96 },
    sent: 8420,
    total: 12000,
    replyRate: 0.032,
    positiveReplies: 94,
    meetings: 11,
    updatedAt: "2026-09-22",
  },
  {
    id: "cmp_print",
    name: "Print houses — referral channel",
    status: "running",
    audience: { source: "csv", label: "1,206 contacts · commercial printers", count: 1206, excluded: 18 },
    sent: 910,
    total: 1206,
    replyRate: 0.044,
    positiveReplies: 21,
    meetings: 6,
    updatedAt: "2026-09-22",
  },
  {
    id: "cmp_homeservices",
    name: "Home services — windows & siding",
    status: "paused",
    pausedReason: "gethubbly.co is missing a DMARC record, so Hubbly stopped sending from it to protect your reputation.",
    audience: { source: "signal", label: "Segment · replacement-window intent", count: 6000, excluded: 140 },
    sent: 3050,
    total: 6000,
    replyRate: 0.021,
    positiveReplies: 19,
    meetings: 3,
    updatedAt: "2026-09-21",
  },
  {
    id: "cmp_returning",
    name: "Returning visitors — no demo booked",
    status: "running",
    audience: { source: "signal", label: "Live list · 3+ visits, no booking", count: 388, excluded: 12 },
    sent: 388,
    total: null,
    replyRate: 0.113,
    positiveReplies: 27,
    meetings: 9,
    updatedAt: "2026-09-23",
  },
  {
    id: "cmp_reactivation",
    name: "Q4 reactivation — past trials",
    status: "draft",
    audience: { source: "csv", label: "1,960 contacts · imported Sep 18", count: 1960, excluded: 0 },
    sent: 0,
    total: 1960,
    replyRate: null,
    positiveReplies: 0,
    meetings: 0,
    updatedAt: "2026-09-18",
  },
];

export const draft: CampaignDraft = {
  campaign: campaigns[0],
  fromLabel: "Rotates across 8 mailboxes on 2 domains",
  savedAt: "2 min ago",
  steps: [
    {
      id: "st_1",
      order: 1,
      dayOffset: 0,
      waitDays: 0,
      sameThread: false,
      variants: [
        {
          id: "v_1a",
          label: "Variant A",
          weight: 50,
          subject: "Saw you on our pricing page",
          body: "Hi {first_name},\n\nSaw {company} took a look at our pricing this week, so I'll keep this short.\n\nHubbly shows you which companies and people visit your site, then follows up for you.\n\nWorth a 15-minute look at what it would find on {website}?\n\nVince",
        },
        {
          id: "v_1b",
          label: "Variant B",
          weight: 50,
          subject: "Quick one, {first_name}",
          body: "Hi {first_name},\n\nYou were comparing plans on our site — happy to answer anything directly.\n\nWant me to run Hubbly on {website} and send you what it finds?\n\nVince",
        },
      ],
    },
    {
      id: "st_2",
      order: 2,
      dayOffset: 2,
      waitDays: 2,
      sameThread: true,
      variants: [
        {
          id: "v_2a",
          label: "Variant A",
          weight: 100,
          subject: "Re: Saw you on our pricing page",
          body: "Hi {first_name},\n\n{Following up on|Circling back to} my note from Monday. You've been on {last_page_viewed} {visit_count} times, so I'm guessing you're comparing options.\n\n[if industry = \"home services\"]Storm season is when this matters most.[else]One question:[end] do you know who's visiting {website} right now? {Most teams|Most owners} we talk to don't — and those visitors are the warmest leads they have.\n\nHubbly shows you the companies and people behind the visits, then follows up for you. Happy to run it on {website} and show you what it finds. Worth 15 minutes this week?\n\nVince",
        },
      ],
    },
    {
      id: "st_3",
      order: 3,
      dayOffset: 7,
      waitDays: 5,
      sameThread: false,
      variants: [
        {
          id: "v_3a",
          label: "Variant A",
          weight: 100,
          subject: "Closing the loop",
          body: "Hi {first_name},\n\nI'll stop here. If knowing who visits {website} ever becomes a priority, just reply and I'll set it up.\n\nVince",
        },
      ],
    },
  ],
};

export const previewContacts: PreviewContact[] = [
  {
    id: "pc_1",
    name: "Dana Ortiz",
    company: "Brightline Dental",
    email: "dana@brightlinedental.com",
    vars: { first_name: "Dana", company: "Brightline Dental", website: "brightlinedental.com", last_page_viewed: "the pricing page", visit_count: "3", industry: "dental" },
  },
  {
    id: "pc_2",
    name: "Marcus Hale",
    company: "Northpoint Roofing",
    email: "marcus@northpointroofing.com",
    vars: { first_name: "Marcus", company: "Northpoint Roofing", website: "northpointroofing.com", last_page_viewed: "the pricing page", visit_count: "3", industry: "home services" },
  },
  {
    id: "pc_3",
    name: "Aaron Wu",
    company: "Peak Plumbing",
    email: "aaron@peakplumbing.co",
    vars: { first_name: "Aaron", company: "Peak Plumbing", website: "", last_page_viewed: "the pricing page", visit_count: "2", industry: "home services" },
  },
];

export const sendChecks: SendCheck[] = [
  { id: "c1", tone: "ok", label: "First name found for every contact", detail: "1,284 / 1,284" },
  { id: "c2", tone: "warn", label: "Website missing for 33 contacts — they'll see \"your site\"", action: "Review" },
  { id: "c3", tone: "ok", label: "No spam-trigger words" },
  { id: "c4", tone: "ok", label: "No links or images — best for a first touch" },
  { id: "c5", tone: "ok", label: "Unsubscribe and address included" },
];

export const leadLists: LeadList[] = [
  { id: "ll_reactivation", name: "Q4 reactivation — past trials", source: "csv", isLive: false, meta: "Sep 18", count: 1960 },
  { id: "ll_pricing", name: "Pricing-page visitors", source: "signal", isLive: true, meta: "Live · updates hourly", count: 1284 },
  { id: "ll_agencies", name: "Marketing agencies, US", source: "csv", isLive: false, meta: "Sep 9", count: 4812 },
  { id: "ll_printers", name: "Commercial printers", source: "csv", isLive: false, meta: "Sep 11", count: 1206 },
  { id: "ll_returning", name: "Returning visitors, no demo", source: "signal", isLive: true, meta: "Live", count: 388 },
];

export const verification: Record<string, VerificationSummary> = {
  ll_reactivation: {
    listId: "ll_reactivation",
    listName: "Q4 reactivation — past trials",
    meta: "CSV import · 1,960 leads · imported Sep 18 · verified Sep 18",
    valid: 1512,
    catchAllVerified: 188,
    risky: 94,
    invalid: 121,
    duplicate: 45,
    readyToSend: 1700,
  },
  ll_pricing: {
    listId: "ll_pricing",
    listName: "Pricing-page visitors",
    meta: "Signal live list · 1,284 leads · verified continuously",
    valid: 1102,
    catchAllVerified: 96,
    risky: 38,
    invalid: 31,
    duplicate: 17,
    readyToSend: 1198,
  },
};

export const leads: Lead[] = [
  { id: "l1", name: "Dana Ortiz", company: "Brightline Dental", email: "dana@brightlinedental.com", emailType: "business", verification: "valid", verificationReason: "Mailbox confirmed", detailsFound: "Website · Phone · Title", lastActivity: "Trial ended Mar 2026" },
  { id: "l2", name: "Chris Mendel", company: "Mendel Law Group", email: "chris@mendellaw.com", emailType: "business", verification: "catch_all_verified", verificationReason: "Recovered by deep check", detailsFound: "Website · Title", lastActivity: "Trial ended Feb 2026" },
  { id: "l3", name: "Aaron Wu", company: "Peak Plumbing", email: "aaron@peakplumbing.co", emailType: "business", verification: "valid", verificationReason: "Mailbox confirmed", detailsFound: "Phone · Title", lastActivity: "Trial ended Jan 2026" },
  { id: "l4", name: "Jessica Lowe", company: "Lowe Realty", email: "info@lowerealty.com", emailType: "business", verification: "risky", verificationReason: "Shared inbox, not a person", detailsFound: "Website · Phone", lastActivity: "Trial ended Apr 2026" },
  { id: "l5", name: "Brian Soto", company: "Soto Landscaping", email: "brian@sotolandscape.net", emailType: "business", verification: "invalid", verificationReason: "Mailbox does not exist", detailsFound: "Website", lastActivity: "Trial ended Dec 2025" },
  { id: "l6", name: "Kim Tran", company: undefined, email: "kimtran.spa@gmail.com", emailType: "personal", verification: "valid", verificationReason: "Mailbox confirmed", detailsFound: "Phone", lastActivity: "Trial ended May 2026" },
  { id: "l7", name: "Ray Castillo", company: "Castillo Auto", email: "ray@castilloauto.com", emailType: "business", verification: "duplicate", verificationReason: "Already in Pricing-page visitors", detailsFound: "Website · Phone", lastActivity: "Visited /pricing Sep 20" },
];

const pricingThreadOut = (name: string, site: string) =>
  `Hi ${name},\n\nYou've been on the pricing page 3 times, so I'm guessing you're comparing options. Do you know who's visiting ${site} right now? Happy to run Hubbly on it and show you. Worth 15 minutes this week?\n\nVince`;

export const replies: Reply[] = [
  {
    id: "r1",
    contactName: "Marcus Hale",
    initials: "MH",
    role: "Owner",
    company: "Northpoint Roofing",
    location: "Austin, TX",
    email: "marcus@northpointroofing.com",
    campaignName: "Pricing-page visitors — 48h follow-up",
    step: 2,
    intent: "meeting_request",
    snippet: "Yes — Thursday afternoon works. Can you show it on our site?",
    receivedAt: "12m",
    owner: "Vince",
    handledByHubbly: false,
    thread: [
      { id: "m1", direction: "out", from: "You · vince@tryhubbly.com", sentAt: "Mon, Sep 21 · 9:12 AM", body: pricingThreadOut("Marcus", "northpointroofing.com") },
      { id: "m2", direction: "in", from: "Marcus Hale · marcus@northpointroofing.com", sentAt: "12 min ago", body: "Yes — Thursday afternoon works. Can you show it on our site? We get a lot of traffic in storm season and have no idea who any of it is.\n\nMarcus" },
    ],
    draftReply: "Thursday works, Marcus. Pick whichever is easier (Central time) and I'll run it live on northpointroofing.com so you can see who's been visiting.",
    timeSlots: ["Thu, Sep 24 · 2:00 PM", "Thu, Sep 24 · 3:30 PM"],
    signalVisits: [
      { path: "/pricing", value: "3 visits" },
      { path: "/signal", value: "Sep 21" },
      { path: "Last visit", value: "2 hours ago" },
    ],
    crm: "Synced to HubSpot",
    history: "Identified by Signal Sep 19 → added to campaign Sep 20 → Step 1 sent Sep 20 → Step 2 sent Sep 21 → replied today",
  },
  {
    id: "r2",
    contactName: "Priya Nair",
    initials: "PN",
    role: "Founder",
    company: "Lumen Studio",
    location: "Denver, CO",
    email: "priya@lumenstudio.co",
    campaignName: "Agencies — partner program",
    step: 1,
    intent: "interested",
    snippet: "What does pricing look like for an agency with 9 clients?",
    receivedAt: "38m",
    owner: "Paul",
    handledByHubbly: false,
    thread: [
      { id: "m3", direction: "out", from: "Paul · paul@hubblyhq.com", sentAt: "Tue, Sep 22 · 10:04 AM", body: "Hi Priya,\n\nAgencies use Hubbly to show clients exactly who visited their sites — and to follow up for them. Open to a partner rate?\n\nPaul" },
      { id: "m4", direction: "in", from: "Priya Nair · priya@lumenstudio.co", sentAt: "38 min ago", body: "What does pricing look like for an agency with 9 clients? Most are local service businesses.\n\nPriya" },
    ],
    draftReply: "Hi Priya — for 9 clients the partner plan is the better fit. I'll send the breakdown per client and a sample report from one of your clients' sites. What's the best one to run it on?",
    signalVisits: [{ path: "/partners", value: "2 visits" }, { path: "Last visit", value: "Yesterday" }],
    crm: "Synced to HubSpot",
    history: "Imported Sep 9 → Step 1 sent Sep 22 → replied today",
  },
  {
    id: "r3",
    contactName: "Tom Becker",
    initials: "TB",
    role: "Owner",
    company: "Becker Print Co.",
    location: "Tulsa, OK",
    email: "tom@beckerprint.com",
    campaignName: "Print houses — referral channel",
    step: 1,
    intent: "interested",
    snippet: "We mail about 40k postcards a month. Would this plug into that?",
    receivedAt: "1h",
    owner: "Paul",
    handledByHubbly: false,
    thread: [
      { id: "m5", direction: "in", from: "Tom Becker · tom@beckerprint.com", sentAt: "1 hour ago", body: "We mail about 40k postcards a month. Would this plug into that?\n\nTom" },
    ],
    draftReply: "It does, Tom — print houses use Hubbly to hand their customers a list of the people who visited their site, ready to mail. Want a 15-minute walkthrough?",
    signalVisits: [{ path: "Last visit", value: "Not identified yet" }],
    history: "Imported Sep 11 → Step 1 sent Sep 22 → replied today",
  },
  {
    id: "r4",
    contactName: "Devon Price",
    initials: "DP",
    role: "Sales manager",
    company: "Atlas Windows",
    location: "Houston, TX",
    email: "devon@atlaswindows.com",
    campaignName: "Home services — windows & siding",
    step: 2,
    intent: "interested",
    snippet: "Can you send over a sample of what you'd find for us?",
    receivedAt: "2h",
    owner: "Vince",
    handledByHubbly: false,
    thread: [
      { id: "m6", direction: "in", from: "Devon Price · devon@atlaswindows.com", sentAt: "2 hours ago", body: "Can you send over a sample of what you'd find for us?\n\nDevon" },
    ],
    draftReply: "Sure, Devon — I'll run it on atlaswindows.com for 48 hours and send you the list of companies and people who visited.",
    signalVisits: [{ path: "/signal", value: "1 visit" }],
    history: "Identified by Signal Sep 15 → Step 2 sent Sep 21 → replied today",
  },
  {
    id: "r5",
    contactName: "Lena Ortiz",
    initials: "LO",
    role: "Practice manager",
    company: "Crestview Dental",
    location: "San Antonio, TX",
    email: "lena@crestviewdental.com",
    campaignName: "Pricing-page visitors — 48h follow-up",
    step: 1,
    intent: "meeting_request",
    snippet: "Does Friday morning work instead? We're slammed Thursday.",
    receivedAt: "3h",
    owner: "Vince",
    handledByHubbly: false,
    thread: [
      { id: "m7", direction: "in", from: "Lena Ortiz · lena@crestviewdental.com", sentAt: "3 hours ago", body: "Does Friday morning work instead? We're slammed Thursday.\n\nLena" },
    ],
    draftReply: "Friday morning works, Lena. Here are two options (Central time).",
    timeSlots: ["Fri, Sep 25 · 9:30 AM", "Fri, Sep 25 · 11:00 AM"],
    signalVisits: [{ path: "/pricing", value: "2 visits" }],
    history: "Identified by Signal Sep 20 → Step 1 sent Sep 22 → replied today",
  },
  {
    id: "r6",
    contactName: "Alisha Grant",
    initials: "AG",
    role: "Marketing lead",
    company: "Harbor Fitness",
    email: "alisha@harborfitness.com",
    campaignName: "Agencies — partner program",
    step: 2,
    intent: "not_now",
    snippet: "Circle back in January — we're in the middle of a rebrand.",
    receivedAt: "4h",
    owner: "Paul",
    handledByHubbly: true,
    thread: [
      { id: "m8", direction: "in", from: "Alisha Grant · alisha@harborfitness.com", sentAt: "4 hours ago", body: "Circle back in January — we're in the middle of a rebrand.\n\nAlisha" },
    ],
    signalVisits: [{ path: "Last visit", value: "Aug 30" }],
    history: "Hubbly scheduled a follow-up for Jan 12",
  },
  {
    id: "r7",
    contactName: "Sam Whitaker",
    initials: "SW",
    role: "Owner",
    company: "Summit HVAC",
    location: "Austin, TX",
    email: "sam@summithvac.com",
    campaignName: "Returning visitors — no demo booked",
    step: 1,
    intent: "interested",
    snippet: "Who else in Austin are you working with?",
    receivedAt: "Yesterday",
    owner: "Paul",
    handledByHubbly: false,
    thread: [
      { id: "m9", direction: "in", from: "Sam Whitaker · sam@summithvac.com", sentAt: "Yesterday", body: "Who else in Austin are you working with?\n\nSam" },
    ],
    draftReply: "Hi Sam — happy to share a couple of local examples on a quick call. Does Monday work?",
    signalVisits: [{ path: "/pricing", value: "4 visits" }],
    history: "Identified by Signal Sep 17 → Step 1 sent Sep 22 → replied yesterday",
  },
];

export const domains: Domain[] = [
  { id: "d_try", name: "tryhubbly.com", origin: "own", connectedAt: "Aug 12", mailboxes: 4, status: "healthy", spf: true, dkim: true, dmarc: true, reputation: "good", dailyLimit: 160 },
  { id: "d_hq", name: "hubblyhq.com", origin: "hubbly", mailboxes: 4, status: "healthy", spf: true, dkim: true, dmarc: true, reputation: "good", dailyLimit: 160 },
  {
    id: "d_get",
    name: "gethubbly.co",
    origin: "own",
    connectedAt: "Sep 14",
    mailboxes: 4,
    status: "needs_fix",
    warmupDay: 9,
    warmupTotal: 21,
    spf: true,
    dkim: true,
    dmarc: false,
    reputation: "building",
    dailyLimit: 40,
    dailyLimitAfterWarmup: 160,
    fix: { record: "DMARC", type: "TXT", host: "_dmarc", value: "v=DMARC1; p=none; rua=mailto:dmarc@gethubbly.co" },
  },
];

const box = (domainId: string, domain: string, local: string, senderName: string, sentToday: number, dailyLimit = 40, health: Mailbox["health"] = "good"): Mailbox => ({
  id: `${domainId}_${local}`,
  domainId,
  address: `${local}@${domain}`,
  senderName,
  sentToday,
  dailyLimit,
  warmupOn: true,
  health,
});

export const mailboxes: Mailbox[] = [
  box("d_hq", "hubblyhq.com", "vince", "Vince at Hubbly", 38),
  box("d_hq", "hubblyhq.com", "paul", "Paul at Hubbly", 36),
  box("d_hq", "hubblyhq.com", "team", "The Hubbly team", 40),
  box("d_hq", "hubblyhq.com", "hello", "Hubbly", 31),
  box("d_try", "tryhubbly.com", "vince", "Vince at Hubbly", 40),
  box("d_try", "tryhubbly.com", "paul", "Paul at Hubbly", 39),
  box("d_try", "tryhubbly.com", "team", "The Hubbly team", 37),
  box("d_try", "tryhubbly.com", "hi", "Hubbly", 24),
  box("d_get", "gethubbly.co", "vince", "Vince at Hubbly", 9, 10, "watch"),
  box("d_get", "gethubbly.co", "paul", "Paul at Hubbly", 8, 10, "watch"),
  box("d_get", "gethubbly.co", "team", "The Hubbly team", 8, 10, "watch"),
  box("d_get", "gethubbly.co", "hello", "Hubbly", 8, 10, "watch"),
];

export const settings: MailSettings = {
  sendInContactTimezone: true,
  sendWindows: "Mon–Fri · 8–11:30 AM, 1–4 PM",
  perMailboxDaily: 40,
  gapMinutes: [4, 9],
  matchProvider: true,
  plainTextFirst: true,
  verifyBeforeSend: true,
  pauseOnBouncePct: 3,
  pauseOnBounce: true,
  trackOpens: false,
  trackClicks: false,
  trackingDomain: "link.tryhubbly.com",
  stopOnReply: true,
  resumeAfterOOO: true,
  assignees: ["Vince", "Paul"],
  draftReplies: true,
  unsubscribeLine: true,
  businessAddress: "2021 Guadalupe St, Austin, TX 78705",
  suppressionCount: 3412,
};
